### ISSUE TITLE
create-react-app option wrongly suggests using `npm run dev`

### ISSUE THREAD

**Issue by fvictorio** [wagmi-dev/create-wagmi#14]
After initializing a project with `npm init wagmi` and selecting the `create-react-app` option, the instructions suggest `cd`ing into the directory and running `npm run dev`, but the project doesn't have a `dev` script (it has a `start` one).

**Comment by tmm** [comment]
Thanks for reporting! Closing this since we removed CRA in favor of [Vite](https://vitejs.dev) moving forward. We find it's a bit better than CRA these days for starting new projects.
