### ISSUE TITLE
`npm init` does not forward options to `create-wagmi`

### ISSUE THREAD

**Issue by 0xOlias** [wagmi-dev/create-wagmi#15]
CLI options passed to `npm init` options are applied to `npm exec`. To forward options to `create-wagmi`, the command in the docs should include a `--`.
```
npm init wagmi -- --template next-with-connectkit
```

Here's a screenshot demonstrating the issue (the `--template` option is not getting passed to `create-wagmi`, hence the prompt)

<img width="585" alt="Screen Shot 2022-11-19 at 5 23 48 PM" src="https://user-images.githubusercontent.com/90073088/202874373-ababb0af-ef5e-4ee0-91d2-35586ab8ec40.png">

(`pnpm create` seems to automatically forward options, not sure about `yarn create`)

**Comment by jxom** [comment]
Fixed! Thanks.
