### ISSUE TITLE
Gitignore does not include .env

### ISSUE THREAD

**Issue by Drewsapple** [wagmi-dev/create-wagmi#34]
Automatically including API keys in the initial commit is quite unhelpful IMO. If a user wants to commit their API keys, they should have to modify gitignore to allow the .env file, instead of forcing them to amend the initial commit to remove its contents.

https://github.com/wagmi-dev/create-wagmi/blob/main/templates/vite-react/rainbowkit/_dot_gitignore I know this is the case with the vite-react-rainbowkit template, but it may apply to other templates.

**Comment by jxom** [comment]
Good catch. Fixed via #35.
