### ISSUE TITLE
Create wagmi with pnpm+Vite+Web3Modal: page doesn't load, (intermediate value).env is undefined error.

### ISSUE THREAD

**Issue by j-chmielewski** [wagmi-dev/create-wagmi#37]
System: Linux - Endeavour OS
Node version: 19.3.0
Pnpm version: 7.19.0

**Reproduce:**

1. Run `pnpm create wagmi`.
2. Choose Vite(React), Web3Modal, valid walletconnect id
3. Cd into app directory
4. `cp .env.example .env`
5. `pnpm dev`

**Effect:**

Blank page, console shows this error:

```
Uncaught TypeError: (intermediate value).env is undefined
    <anonymous> wagmi.ts:8
[wagmi.ts:8:12](http://127.0.0.1:5173/[...]/src/wagmi.ts)
    <anonymous> wagmi.ts:8
```

**Workaround:**

Altering chains array so that it doesn't use `import.meta.env.NODE_ENV` variable fixes the issue.

**Comment by jxom** [comment]
Fixed on `0.1.11`.
