### ISSUE TITLE
Wagmi generate with foundry does not work

### ISSUE THREAD

**Issue by Preston-Harrison** [wagmi-dev/create-wagmi#51]
When running `yarn wagmi` on the standard cli-foundry remplate, I get the following:
![Screenshot 2023-01-31 at 9 57 56 pm](https://user-images.githubusercontent.com/87624649/215963481-6fe740ee-21ec-40ef-9f7e-9c0ccae3f795.png)

**Comment by Preston-Harrison** [comment]
Fixed by explicitly setting `artifacts: "out/"`. I think this is a result of using strings to join the project directory with the artifact directory. Instead, it would be better to use `path.join`

**Comment by tmm** [comment]
@Preston-Harrison Mind creating a minimal reproducible example? Happy to take a look.

**Comment by Preston-Harrison** [comment]
It happens in the sample template

**Comment by Preston-Harrison** [comment]
https://github.com/wagmi-dev/wagmi/blob/main/packages/cli/src/plugins/foundry.ts#L154

I think should be path.join()

**Comment by tmm** [comment]
Issue was from the `foundry.toml#out` option being appended to Foundry plugin's `project` property, resulting in `contracts/contracts/out`. Added automatic detection for the Foundry config file to fix this: https://github.com/wagmi-dev/wagmi/pull/1779
